### ISSUE TITLE
HTTPS problem

### ISSUE THREAD

**Issue by YvesChan** [slixurd/oj#2]
check base_url() function implement in system/core/Config.php, it's related to a _server['HTTPS'] vars, but it has been set ?!

check this docs: https://github.com/EllisLab/CodeIgniter/wiki/Automatic-configbase-url or you have another better solution?

**Comment by slixurd** [comment]
This question causes by NGINX,
Leaving the config/config.php $config['base_url'] space can make it distinguish the url itself

**Comment by YvesChan** [comment]
But when I deploy the project on VM, it does have this problem with empty $config['base_url'], then solve it through the docs above. So you have not meet this problem before? (with nginx)
@slixurd

**Comment by slixurd** [comment]
I only use Apache ww
